### PR TITLE
addNostrTools2

### PR DESCRIPTION
**Pull request by xrviv**

### CODE REVIEW

**Comment by xrviv** [comment]
It's showing only 1 file changed...

https://nosbin.com/nevent1qqsfvw3q7urt2vxxe5rldrz8j85sawnp7kmx2vxwllykjr4kqzl54hspzemhxue69uhkzarvv9ejumn0wd68ytnvv9hxgqg4waehxw309ajkgetw9ehx7um5wghxcctwvsq3wamnwvaz7tmwdaehgu3wvekhgtnhd9azucnf0gq3gamnwvaz7tmwdaehgu3wdau8gu3wv3jhvqgswaehxw309ahx7um5wgh8w6twv5q3jamnwvaz7tmwdaehgu3w0fjkyetyv4jjucmvda6kgqghwaehxw309aex2mrp0yhxxatjwfjkuapwveukjqg5waehxw309aex2mrp0yhxgctdw4eju6t0qyt8wumn8ghj7un9d3shjtnwdaeky6tw9e3k7mgprfmhxue69uhhyetvv9ujummjv9hxwetsd9kxctnyv4mqzxrhwden5te0wfjkccte9eekummjwsh8xmmrd9skcjjyr58

**Comment by Giszmo** [comment]
Yes. The one "file" changed is the submodule. Adding content happens over there and not here.

**Comment by xrviv** [comment]
Sorry, so, is this the correct process?:

- fork Giszmo/nostrResources
- git clone Giszmo/nostrResources
- create a branch
- make the changes 
- push to my remote
- make a MR pointed to nostrResources

**Comment by Giszmo** [comment]
But you did that already, didn't you? The other PR that you deleted worked like that. You just had an accident where you added many files from Jekyll cache ...

**Pull request closed without merging**
